server:
  port: 8062

spring:
  application:
    name: media-service
  datasource:
    url: jdbc:postgresql://localhost:5442/media_db
    username: media
    password: media
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true

minio:
  url: http://localhost:9000
  accessKey: minio
  secretKey: minio123
  bucket: fitness-tracker

keycloak:
  server-url: http://localhost:8089
  realm: master
  client-id: admin-cli
  username: admin
  password: admin
  target.realm: scassets
  target.client: scassets-client

  auto-create: true  # set true for role creation during program start

  predefined-roles:
    roles:
      # About
      - name: formulas_edit
      - name: roles_view
      - name: pool_view
      # Account
      - name: accounts_view
      - name: accounts_edit
      # Car
      - name: cars_view
      - name: cars_edit
      # Contractor
      - name: contractors_view
      - name: contractors_edit
      # Counter
      - name: counters_view
      - name: counters_edit
      # Division
      - name: divisions_view
      - name: divisions_edit
      # DocAction
      - name: docactions_view
      - name: docationss_edit
      # DocType
      - name: doctypes_view
      - name: doctypes_edit
      # Document
      - name: documents_view
      - name: documents_edit
      - name: documents_process
      # Driver
      - name: drivers_view
      - name: drivers_edit
      # HistoryLog
      - name: logs_view
      # Init
      - name: settings_view
      - name: settings_edit
      # Location
      - name: locations_view
      - name: locations_edit
      # Measure
      - name: measures_view
      - name: measures_edit
      # Metal
      - name: metals_view
      - name: metals_edit
      # MetalGroup
      - name: metalgroups_view
      - name: metalgroups_edit
      # Nomenclature
      - name: nomenclatures_view
      - name: nomenclatures_edit
      # NomenclatureGroup
      - name: nomenclaturegroups_view
      - name: nomenclaturegroups_edit
      # OperationType
      - name: operationtypes_view
      - name: operationtypes_edit
      # Person
      - name: people_view
      - name: people_edit
      # Storage
      - name: storages_view
      - name: storages_edit
      # StorageCard
      - name: storagecards_view
      - name: storageaccountable_view       #
      - name: storagecards_edit

    # Композитные роли (необязательно)
    composite-roles:
      - name: documents_manager
        included-roles:
          - documents_view
          - documents_edit
          - documents_process


logging:
  level:
#    org.apache.http.impl.execchain.MainClientExec: INFO

#    org.apache.http.wire: DEBUG  # Логирует все HTTP запросы/ответы
    org.apache.http.headers: DEBUG  # Логирует заголовки
#    org.keycloak.admin.client: DEBUG  # Логи Keycloak клиента
#    org.jboss.resteasy.client: DEBUG  # RESTEasy клиент

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8089/realms/depo-clone

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.postgresql.jdbc: TRACE
#    org.postgresql.sql: DEBUG