server:
  port: 8062

spring:
  application:
    name: media-service
  datasource:
    url: jdbc:postgresql://localhost:5442/media_db
    username: media
    password: media
  flyway:
    enabled: true
    locations: classpath:db/migration
  jpa:
    show-sql: true

minio:
  url: http://localhost:9000
  accessKey: minio
  secretKey: minio123
  bucket: fitness-tracker

keycloak:
  server-url: http://localhost:8089
#  server-url: https://sc-map-test.softclub.by:7891/auth
  realm: master
  client-id: admin-cli
  username: admin
#  password: sh82bKpwcSds
  password: admin
  target.realm: scassets-test
  target.client-id: scassets-test-client
#  target.realm: scassets
#  target.client-id: scassets-client

  auto-create: true
  default-user:
    username: root
    email: root@gmail.com
    password: root
    firstName: r
    lastName: r
    roles: admin
  predefined-roles:
    roles:
      # About
#      - name: formula_edit
#        description: "Редактирование формулы"
#      - name: role_view
#        description: "Просмотр роли"
      # Account
      - name: account_view
        description: "Просмотр аккаунта"
      - name: account_edit
        description: "Редактирование аккаунта"
      # Car
      - name: car_view
        description: "Просмотр автомобилей"
      - name: car_edit
        description: "Редактирование автомобилей"
      # Contractor
      - name: contractor_view
        description: "Просмотр контрагентов"
      - name: contractor_edit
        description: "Редактирование контрагентов"
      # Counter
      - name: counter_view
        description: "Просмотр счетчиков"
      - name: counter_edit
        description: "Редактирование счетчиков"
      # Division
      - name: division_view
        description: "Просмотр подразделений"
      - name: division_edit
        description: "Редактирование подразделений"
      # DocAction
      - name: doc_action_view
        description: "Просмотр действий с документами"
      - name: doc_action_edit
        description: "Редактирование действий с документами"
      # DocType
      - name: doc_type_view
        description: "Просмотр типов документов"
      - name: doc_type_edit
        description: "Редактирование типов документов"
      # Document
      - name: document_view
        description: "Просмотр документов"
      - name: document_edit
        description: "Редактирование документов"
      - name: document_process
        description: "Обработка документов"
      - name: operation_view
        description: "Просмотр операций"
      # Driver
      - name: driver_view
        description: "Просмотр водителей"
      - name: driver_edit
        description: "Редактирование водителей"
      # HistoryLog
      - name: log_view
        description: "Просмотр журнала изменений"
      # Init
      - name: setting_edit
        description: "Редактирование настроек"
      # Location
      - name: location_view
        description: "Просмотр местоположений"
      - name: location_edit
        description: "Редактирование местоположений"
      # Measure
      - name: measure_view
        description: "Просмотр единиц измерения"
      - name: measure_edit
        description: "Редактирование единиц измерения"
      # Metal
      - name: metal_view
        description: "Просмотр металлов"
      - name: metal_edit
        description: "Редактирование металлов"
      # MetalGroup
      - name: metal_group_view
        description: "Просмотр групп металлов"
      - name: metal_group_edit
        description: "Редактирование групп металлов"
      # Nomenclature
      - name: nomenclature_view
        description: "Просмотр номенклатуры"
      - name: nomenclature_edit
        description: "Редактирование номенклатуры"
      # NomenclatureGroup
      - name: nomenclature_group_view
        description: "Просмотр групп номенклатуры"
      - name: nomenclature_group_edit
        description: "Редактирование групп номенклатуры"
      # OperationType
      - name: operation_type_view
        description: "Просмотр типов операций"
      - name: operation_type_edit
        description: "Редактирование типов операций"
      # Person
      - name: people_view
        description: "Просмотр матответственных"
      - name: people_edit
        description: "Редактирование матответственных"
      # Storage
      - name: storage_view
        description: "Просмотр складов"
      - name: storage_edit
        description: "Редактирование складов"
      # StorageCard
      - name: storage_card_view
        description: "Просмотр складских карточек"
      - name: storage_card_accountable_view
        description: "Просмотр складских карточек в подотчете"
      - name: storage_card_edit
        description: "Редактирование складских карточек"
      - name: storage_card_doc_view
        description: "Просмотр складских карточек в документах"
      # Role
      - name: role_view
        description: "Просмотр ролей"
      - name: role_edit
        description: "Редактирование ролей"
    # Композитные роли
    composite-roles:
      - name: STOREKEEPER
        description: "Кладовщик"
        included-roles:
          - measure_view
          - measure_edit
          - nomenclature_view
          - nomenclature_edit
          - nomenclature_group_view
          - nomenclature_group_edit
          - storage_view
          - storage_edit
          - people_view
          - people_edit
          - doc_type_view
          - doc_type_edit
          - contractor_view
          - contractor_edit
          - car_view
          - car_edit
          - driver_view
          - driver_edit
          - location_view
          - location_edit

          - setting_edit
          - counter_view
          - counter_edit

          - storage_card_accountable_view
          - storage_card_view
          - storage_card_edit
          - storage_card_doc_view
          - document_view
          - document_edit
          - operation_view
      - name: BOOKKEEPER
        description: "Бухгалтер"
        included-roles:
          - storage_view
          - storage_edit
          - people_view
          - people_edit
          - account_view
          - account_edit
          - division_view
          - division_edit
          - contractor_view
          - contractor_edit
          - doc_type_view
          - doc_type_edit

          - setting_edit
          - counter_view
          - counter_edit
          - doc_action_view
          - doc_action_edit
          - log_view
          - operation_type_view
          - operation_type_edit

          - storage_card_accountable_view
          - storage_card_view
          - storage_card_edit
          - storage_card_doc_view
          - document_view
          - document_edit
          - document_process
          - operation_view
      - name: VIEWER
        description: "Просмотр данных"
        included-roles:
          - account_view
          - car_view
          - contractor_view
          - division_view
#          - doc_action_view       // убрать
          - doc_type_view
          - driver_view
          - location_view
          - measure_view
          - nomenclature_view
          - nomenclature_group_view
          - people_view
          - storage_view

          - counter_view
          - doc_action_view

          - storage_card_view
          - document_view
          - operation_view
      - name: CATALOGER
        description: "Работа со справочниками"
        included-roles:
          - account_view
          - account_edit
          - car_view
          - car_edit
          - contractor_view
          - contractor_edit
          - division_view
          - division_edit
          - doc_action_view
          - doc_action_edit
          - doc_type_view
          - doc_type_edit
          - driver_view
          - driver_edit
          - location_view
          - location_edit
          - measure_view
          - measure_edit
          - nomenclature_view
          - nomenclature_edit
          - nomenclature_group_view
          - nomenclature_group_edit
          - people_view
          - people_edit
          - storage_view
          - storage_edit
          - metal_view
          - metal_edit
          - metal_group_view
          - metal_group_edit
      - name: ADMIN
        description: "Администратор (включает все объекты)"
        included-roles:
          - account_view
          - account_edit
          - car_view
          - car_edit
          - contractor_view
          - contractor_edit
          - division_view
          - division_edit
          - doc_action_view
          - doc_action_edit
          - doc_type_view
          - doc_type_edit
          - driver_view
          - driver_edit
          - location_view
          - location_edit
          - measure_view
          - measure_edit
          - nomenclature_view
          - nomenclature_edit
          - nomenclature_group_view
          - nomenclature_group_edit
          - people_view
          - people_edit
          - storage_view
          - storage_edit
          - metal_view
          - metal_edit
          - metal_group_view
          - metal_group_edit
          - setting_edit
          - counter_view
          - counter_edit
          - log_view
          - operation_type_view
          - operation_type_edit
          - document_view
          - document_edit
          - document_process
          - operation_view
          - storage_card_view
          - storage_card_edit
          - storage_card_accountable_view
          - storage_card_doc_view
          - role_view
          - role_edit
logging:
  level:
    org.apache.http.wire: DEBUG  # Логирует все HTTP запросы/ответы
#    org.apache.http.impl.execchain.MainClientExec: INFO
#    org.apache.http.headers: DEBUG  # Логирует заголовки
#    org.keycloak.admin.client: DEBUG  # Логи Keycloak клиента
#    org.jboss.resteasy.client: DEBUG  # RESTEasy клиент

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8089/realms/depo-clone

#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.postgresql.jdbc: TRACE
#    org.postgresql.sql: DEBUG